### ISSUE TITLE
Feature Request: Vertical option and overflow: visible option

### ISSUE THREAD

**Issue by paultannenbaum** [thebird/Swipe#173]
Hi Brad, 

I am using a modified version of this in a personal project and have added two options to the slider, The ability to make the slider run vertical instead of horizontal, and a overflow option which is a simple boolean flag that will prevents the js from setting overflow: hidden on the parent container. This is useful for trying to create an effect like a slot machine. Anyhow, wanted to see if you are interested in having these be a part of the main project. If so, let me know and I will submit a pull request (it will have to be off a fresh fork as my current one has some other project related setting in there).

Thanks for the plugin!

**Comment by Zhang-Yida** [comment]
@paultannenbaum  could you please show the vertical swipe plugin demo or codes ?  Thank you first!
