### ISSUE TITLE
iframes inside slides

### ISSUE THREAD

**Issue by niksy** [thebird/Swipe#36]
I’m trying to put iframe player from YouTube and Vimeo but SwipeJS behaves very strange when you put iframes as content inside slides.
- it seems like iframe is catching all touch events so only way you can swipe left/right is when you touch area outside iframe
- YouTube player acts very strange in a way that it doesn’t show iframe content but when you tap on empty area player activates and upon pausing video everything shows correctly

I’ve tried with their respective JS APIs but, as with iframes, they’re also very buggy and "beta-ish" so support is not standardized across platforms.

**Comment by myst1349** [comment]
@qnp - Could you please attach jsfiddle example or explain what are ".overlays" and ".wrapper" elements?

**Comment by qnp** [comment]
Say your galery is `#galery`, where inside you have `.wrapper`. You instanciate your Swipe with `var swipe = Swipe($('#galery')[0],{options});`. This object will use the first child which is `.wrapper`, which listens to the swipe events.

Your overlays are divs that are transparent and in front of the `#galery`. Then you listen the touch events on `.overlays`and pass them (with the function `passTouchEvent`I presented before) to the `.wrapper`:
`$('.overlays').bind('touchstart touchmove touchend', function(e){
        passTouchEvent(e,$(.wrapper));
      });`
I hope this helps.

**Comment by Aybee** [comment]
Ok, then I think best way will be that the admin provides an extra visual horizontal stripe on which you can slide an iframe if someone really wants youtube in a slider.

**Comment by DjulLau** [comment]
I went this route too (well, the other way around, forwarding click events from my transparent cover to the iframes) but I'm still searching for a better alternative as it prevents too much things from happening in the iframe content (hovers, drag n' drops etc.). 
Wonder if there is any way to let the iframe consume the events it needs and forward the rest to the swiper instance like in a normal webpage flow (I'm in a desktop/nw.js app so domain should not be a problem). 
If anyone has an idea I would be eternally grateful :)
