### ISSUE TITLE
Disable 'bounce' or 'elastic stretch' effect?

### ISSUE THREAD

**Issue by crsrusl** [thebird/Swipe#413]
Hi guys

Is there a way to disable the bounce effect - ?

Cheers

Chris

**Comment by aelor** [comment]
adding return false will disable slide animation for all the cases, for just disabling the elastic effect at the ends check a condition for start and end and then do return false accordingly at line 322 where delta.x is defined write the following code before it

    if(!index && delta.x > 0 || (index == slides.length - 1) && delta.x < 0){
        		return false;
    }
