### ISSUE TITLE
swipe.js dead?

### ISSUE THREAD

**Issue by alexplusde** [thebird/Swipe#460]
So many opened issues, website not working... should i still consider swipe.js? I wanted to use it because it works without jquery.

**Comment by olimsaidov** [comment]
use more advanced robust slider https://github.com/dimsemenov/PhotoSwipe

**Comment by cferdinandi** [comment]
@olimsaidov Are you kidding, dude? PhotoSwipe looks AWESOME! Really nice work!

Everyone else: I tried reaching out to @thebird on Twitter and got no response. I haven't seen any commits, updates, or even merged PR's on this projects in over a year. I think it's same to assume it's been abandoned, and I've discontinued development on Slider, my fork of Swipe. 

Going forward, I think I'll try PhotoSwipe on my next project that requires it.

**Comment by lyfeyaj** [comment]
@arcxyz Yes, Swipe is much smaller than other choices, and it is kind of dead. I don't know how can I reach the author to help maintain this project. So, I start to maintain my own fork of this project with some bug-fixes and new features
<https://github.com/lyfeyaj/swipe>
Welcome to submit PR, Feature request and issues

**Comment by cferdinandi** [comment]
All, I just stumbled upon [this new, vanilla JS friendly alternative](https://github.com/nolimits4web/swiper/) that may be worth taking a look at.

Swiper: https://github.com/nolimits4web/swiper/

**Comment by evolutionxbox** [comment]
[Flickity JS](http://flickity.metafizzy.co/). The best, smoothest, and most natural feeling Carousel/Slider yet.

**Comment by jackbarham** [comment]
I can confirm that switching to https://github.com/lyfeyaj/swipe has fixed all my issues and I didn't have to update any local js changes.
