### ISSUE TITLE
published to npm as swipe-js

### ISSUE THREAD

**Issue by nickleefly** [thebird/Swipe#486]
published to npm as [swipe-js](https://www.npmjs.com/package/swipe-js)

**Comment by nickleefly** [comment]
pr #487

**Comment by lyfeyaj** [comment]
Hi @nickleefly , I maintain a dependent version of swipe, could you have a look at <https://github.com/lyfeyaj/swipe>, and if possible submit a pull request for your bugfixes or features, many thanks. Maybe we can work together to make this project alive again.

**Comment by nickleefly** [comment]
Hi @lyfeyaj, I can add you as a Collaborator

**Comment by sarazhang123** [comment]
Hi @nickleefly , I use swipe.js, on computer web page, carousel speed is normal, but on mobile web page, carousel speed is quicker. How I fix this issue?
You can see this situation on mobile or computer.

**Comment by nickleefly** [comment]
@sarazhang123 you can add in `speed` in config options
