### ISSUE TITLE
mySwipe.getNumSlides return 3, 2, 1, 0 when elements number is 2

### ISSUE THREAD

**Issue by EIA** [thebird/Swipe#504]
Hi,

I simplify the index.html
when mySwipe.getNumSlides is 2,
mySwipe.getNumSlides will return 3, 2, 1, 0

here's a screenshot
![image](https://cloud.githubusercontent.com/assets/1102087/10222586/712fcacc-6887-11e5-9b7e-ead2ae75977d.png)

**Comment by lyfeyaj** [comment]
@EIA , Hi you can try https://github.com/lyfeyaj/swipe, an active developing fork of this project which have this issue fixed.
